### ISSUE TITLE
Should allow the device type to be specified in `models.device.register()`

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-sdk#1009]
When using the CLI's `balena device register` command, the user would like to specify the device type which may be different from the application's type. For example, the user would like to register a `raspberrypi3` (RPi 3) device on a `raspberry-pi` (RPi 1) application:

* https://github.com/balena-io/balena-cli/issues/1918
* https://www.flowdock.com/app/rulemotion/public-s-community/threads/NfRTeBfpHfmIeB9FmOaTA9sCmCa

Node SDK code:
* https://github.com/balena-io/balena-sdk/blob/v15.12.1/lib/models/device.ts#L2161

CLI code:
* https://github.com/balena-io/balena-cli/blob/v12.23.3/lib/commands/device/register.ts#L78

**Comment by thgreasi** [comment]
Resolved by #1271
