### ISSUE TITLE
Should support querying applications by UUID

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-sdk#1016]
The balena API has support for querying applications by UUID:
https://github.com/balena-io/open-balena-api/pull/491/files

The SDK should support this too. As for the model interface / function signatures, given that UUIDs and app names are both strings that cannot be readily unambiguously distinguished, the SDK should provide a way for the caller to explicitly specify whether the identifier is a UUID or application, for example:

```
application.get({ uuid: 'decade2' }, opts)
```

Some additional discussion took place in a [private thread](https://www.flowdock.com/app/rulemotion/i-cli/threads/g26bVg0Nc518ZZknqxtX0GmWhwb). Extract:

> Any application name with exactly 32 or 62 characters in the set `[a-fA-F0-9]` would be indistinguishable from an application UUID (while not necessarily being a UUID, or at least not a UUID in balena's database, perhaps a UUID in the user's own database), and thus subject to a query error. It's a rare corner case, but we are better off avoiding them. It would be an unnecessary restriction to tell users that they shouldn't name applications with 32 or 62 characters from a particular character set. I like `application.get({ uuid: '123456' }, opts)` better than trial-and-error heuristic probabilistic auto detection. :-)

> There is also the case of short UUIDs. For device UUIDs, I gather that the SDK currently issues a filtered query with `$startswith: uuidOrId`:  
> https://github.com/balena-io/balena-sdk/blob/v15.17.0/lib/models/device.ts#L514
> For devices, the SDK only needs to do this when the UUID is not a number (JS data type), so at least it knows that the short UUID is actually a UUID. With applications, 7-char UUIDs would more easily be confused with names. For example, the word "decade2" is both a valid app name and valid short UUID. I am OK with the occasional conflict and error if the user _chooses_ to use an ambiguous command line option/syntax like `--application decade2` (in fact in this thread I have voiced my preference to keep allowing this kind of auto detection for backwards compatibility even in future major versions of the CLI, when others suggested that the next major version of the CLI should disallow auto detection / ambiguous identifier specification). But I also think that the SDK and the CLI should provide a way of unambiguously specifying whether the identifier is a name, UUID or database ID. So while the SDK could provide the feature of best effort filtering by long UUID, short UUID, app name, slug and database ID, I think there should also be a way of querying only by a specific identifier type like UUID. Like `application.get({ uuid: 'decade2' }, opts)`.

See: https://www.flowdock.com/app/rulemotion/i-cli/threads/g26bVg0Nc518ZZknqxtX0GmWhwb

**Comment by thgreasi** [comment]
The open-balena-api has support for querying the application's uuid.
At the cloud API doesn't expose the application uuid in the v6 model.

**Comment by thgreasi** [comment]
That's now on v6
See: https://github.com/balena-io/balena-api/pull/2981

**Comment by thgreasi** [comment]
Splitted the alternate key object notation to:
See: https://github.com/balena-io/balena-sdk/issues/1176
