### ISSUE TITLE
Uncaught exception when setting Supervisor version

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-sdk#1065]
When trying to update the Supervisor for a device via the SDK method: `sdk.models.device.setSupervisorRelease('<device uuid>', 'v12.3.5')` we got the following error:

```
Uncaught (in promise) Error: Incompatible supervisor version: 6.3.6 - must be >= 7.0.0
    z device.js:136
    setSupervisorRelease device.js:2625
    a tslib.es6.js:71
    promise callback*u tslib.es6.js:73
    l tslib.es6.js:74
    l tslib.es6.js:70
    setSupervisorRelease device.js:2613
    n callbacks.js:18
    <anonymous> debugger eval code:1
device.js:136:18
```

This device was upgraded from balenaOS 2.7.5+rev1 to 2.69.1+rev1 and most of the OS seems current except the Supervisor so we wanted to manually update it via the SDK.

**Comment by 20k-ultra** [comment]
Is there no way then to upgrade the Supervisor version in the API ? This error seems to be by design so I don't expect a patch to be created.

**Comment by thgreasi** [comment]
@xginn8 I think this one is for you.
@20k-ultra we officially don't support supervisor updates for such old pre-MC supervisor releases.
The bug you faced, which cascaded here, is probably that the supervisor was not updated after HUP, which sounds like we should investigate any way.

A way to have the method also work for such "incomplete hup" cases, could be to first check the OS version and allow it if it's recent enough and it's just the supervisor that is on an old version. But for that we will need first Matt to confirm whether that's something that's safe to allow or whether we should prefer fixing it on support only.

**Comment by xginn8** [comment]
I'd much rather fix these in support, rather than some workaround. We only prevent these upgrades via the self-serve mechanism, as HUP can still patch directly to upgrade the supervisor outside the SDK.
