### ISSUE TITLE
SDK should support device actions

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-sdk#266]

**Comment by thgreasi** [comment]
@pimterry Is it just the device os update & perhaps the device deactivation that are missing, or do we intend to have a generic device-actions implementation?

- [ ] deactivate device
- [ ] os update
- [x] identify
- [x] purge
- [x] reboot
- [x] restartApplication
- [x] shutdown
- [x] startApplication
- [x] stopApplication

**Comment by thgreasi** [comment]
Closing since all device actions are now supported (even hup) except from device-deactivation.
