### ISSUE TITLE
Default to image maker URL from the API config

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-sdk#495]
Right now, the default image maker URL is independent of the passed API URL. This means if you pass `apiUrl: 'api.resinstaging.io'` when setting up the SDK constructor, you'll actually still be using `img.resin.io` as your image maker, which likely isn't what you expect.

We should definitely change that default behaviour, and it's clearly confusing and wrong.

We could maybe kill the separate configurability of the image maker URL entirely - I don't know of any good reasons why you would want to use an image maker from one environment with the API from another. We should investigate that a little more first though.

**Comment by thgreasi** [comment]
The SDK no longer uses the image maker. Closing.
