### ISSUE TITLE
Add method to set a single device to a particular release

### ISSUE THREAD

**Issue by amdomanska** [balena-io/balena-sdk#573]
Goal: There should be a method that lets to set the single device to a particular release similar to:
https://github.com/resin-io-playground/staged-releases/blob/master/set-device-to-a-build.sh

Implementation: Release Id should be set as a value for a should_be_running__release param (eg by pine.patch request)

To be discussed: corresponding method setApplicationToRelease uses fullHashCommit as a param from a user. setDeviceToRelease method probably should accept that as well - instead of releaseId that is not easily accessible by a user. Question is: can we be sure that commitHash <-> ReleaseId pairs are not ambiguous (that the are no 2 releases for single commit hash for example).

**Comment by amdomanska** [comment]
it's a follow up for: https://github.com/resin-io/resin-sdk/pull/572

**Comment by pimterry** [comment]
> Question is: can we be sure that commitHash <-> ReleaseId pairs are not ambiguous (that the are no 2 releases for single commit hash for example).

@amdomanska For this, you need to start looking at the rules in the SBVR. If you look at https://github.com/resin-io/resin-api/blob/master/src/models/resin.sbvr#L1238, it says:

> Rule: It is necessary that each release1 that has a status that is equal to "success" and has a commit1, belongs to an application that owns exactly one release2 that has a status that is equal to "success" and has a commit2 that is equal to the commit1.

What that means in practice is that there is at max one _successful_ release in the application for a given commit hash. There might be other failed releases, but fortunately we don't care about them - when pinning a release like this we'll always want to use the successful one.

**Comment by thgreasi** [comment]
This was resolved by #572
