### ISSUE TITLE
Method to disable rolling updates for deployed machines

### ISSUE THREAD

**Issue by Lucaszw** [balena-io/balena-sdk#606]
Modified via feedback from PR #607 

It would be nice to have the functionailty fo ```application.disable_rolling_updates``` available in the node.js API.

Something like:
```js
application.disableTrackLatestRelease(nameOrId)
```

https://github.com/balena-io-projects/staged-releases/blob/master/disable-rolling-release-on-fleet.sh

```sh
curl -X PATCH "https://api.$BASE_URL/v4/application($APP_ID)" -H "Authorization: Bearer $authToken" -H "Content-Type: application/json" --data-binary '{"should_track_latest_release":false}'
```

https://github.com/balena-io/balena-sdk-python/blob/master/balena/models/application.py

```python
    def disable_rolling_updates(self, app_id):
        """
        Disable Rolling update on application.
        Args:
            name (str): application id.
        Returns:
            OK/error.
        Raises:
            ApplicationNotFound: if application couldn't be found.
        Examples:
            >> > balena.models.application.disable_rolling_updates('106640')
            'OK'
        """

        params = {
            'filter': 'id',
            'eq': app_id
        }
        data = {
            'should_track_latest_release': False
        }

        return self.base_request.request(
            'application', 'PATCH', params=params, data=data,
            endpoint=self.settings.get('pine_endpoint')
        )
```

**Comment by Lucaszw** [comment]
This looks like it can be done w/ the .update() methods; closing for now

**Comment by thgreasi** [comment]
A way to achieve this was added by https://github.com/balena-io/balena-sdk/pull/572 in v11.1.0 .
You can now achieve this by using `balena.models.application.pinToRelease('MyApp', 'f7caf4ff80114deeaefb7ab4447ad9c661c50847');`
