### ISSUE TITLE
Support for web-based authentication

### ISSUE THREAD

**Issue by wlisac** [balena-io/balena-sdk#634]
I'd like to use the Balena SDK with web-based authentication instead of a username and password flow.

Currently this is only supported for the Balena CLI and not available to third party consumers.

There are several benefits to supporting a web based flow – a few include:
- The user does not share credentials directly with the third party client
- The user may already be logged into balena's website (or use a browser's password autofill)
- Easier support for MFA and third party auth providers (GitHub or Google)

In the short term, this could be enabled by allowing the SDK to use a similar login flow as CLI tool.

Longer term, support for OAuth authorization code flow with the PKCE extension would be _really nice_ for third party public clients (beyond using sdk).

**Comment by thgreasi** [comment]
Hi @wlisac 
The CLI allows web-bases authentication by [starting a local web-server](https://github.com/balena-io/balena-cli/blob/01eb4b473de40dec0aa2ee77d599239c222c5b1a/lib/auth/index.coffee#L46-L63) and then eventually uses [the SDK's `.loginWithToken()` method](https://github.com/balena-io/balena-sdk/blob/master/DOCUMENTATION.md#balena.auth.loginWithToken) with the token that the user will provides access to. Given that adding a web-server as a dependency of the SDK would result an increased bundle size, such a method was left to be implemented b

The suggested approach currently, is similar to the  `.loginWithToken()`

**Comment by thgreasi** [comment]
@wlisac I just updated my earlier comment after an accidental touchpad click.
Please give us a note if the above do not cover your use case or think that having a separate wrapper for the SDK is not a good approach for the use cases that you mentioned.

**Comment by wlisac** [comment]
@thgreasi thanks for the detailed reply. I can understand definitely understand why we wouldn't want to add a web server to the SDK to mirror the CLI's log in flow.

I've opened a post on the forums with some additional context around my auth use case since it's not necessarily SDK specific :)


- Will

**Comment by wlisac** [comment]
@thgreasi thanks for the detailed reply. I can definitely understand why we wouldn't want to add a web server to the SDK to mirror the CLI's log in flow.

I've opened a post on the forums with some additional context around my auth use case since it's not necessarily SDK specific :)

https://forums.balena.io/t/balena-oauth-api-or-other-log-in-api/12913/2

Thanks for the help,
Will
