### ISSUE TITLE
Run mocha with `--forbid-only` as part of the CI testing

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-sdk#651]
In order to prevent accidental `only` testing commits, allow mocha to forbid these modifications (see https://github.com/balena-io/balena-sdk/pull/650)

**Comment by thgreasi** [comment]
We now do run `lint` with the `--tests` flag, which replaced the `--forbid-only` one in the latest balena-lint.
See: https://github.com/balena-io/balena-sdk/blob/1a3b05c4637f19fc5f219337fc48df113d0530d7/package.json#L50
