### ISSUE TITLE
Localstorage error when run in AWS Lambda

### ISSUE THREAD

**Issue by concreted** [balena-io/balena-sdk#652]
## Expected Behavior
Balena SDK should work in an AWs Lambda environment

## Actual Behavior
When run in a Lambda, execution fails with the following stack trace:
```
{
  "errorMessage": "ENOENT: no such file or directory, mkdir '/home/sbx_user1051/.balena'",
  "errorType": "Error",
  "stackTrace": [
    "LocalStorage._init (/var/task/node_modules/node-localstorage/LocalStorage.js:156:14)",
    "new LocalStorage (/var/task/node_modules/node-localstorage/LocalStorage.js:121:12)",
    "createStorage (/var/task/node_modules/balena-settings-storage/build/local-storage.js:97:16)",
    "getStorage (/var/task/node_modules/balena-settings-storage/build/storage.js:39:24)",
    "new BalenaAuth (/var/task/node_modules/balena-auth/build/auth.js:191:24)",
    "getSdk (/var/task/node_modules/balena-sdk/build/balena.js:95:10)",
    "Object.<anonymous> (/var/task/handler.js:5:35)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}
```

## Steps to Reproduce the Problem

1. Create a lambda and import the Balena SDK:
```
var balena = require('balena-sdk')({
    apiUrl: "https://api.balena-cloud.com/"
});
```

## Specifications

- SDK version: 11.9.0
- Browser: Node only
- Node version: 8.10 (AWS Lambda)
- Npm version: Version running in AWS Lambda env
- OS: AWS Lambda

**Comment by pdcastro** [comment]
It may be possible to specify the `dataDirectory` option under `/tmp`, which I gather exists in the AWS Lambda local file system:
```
var balena = require('balena-sdk')({
	apiUrl: "https://api.balena-cloud.com/",
	dataDirectory: "/tmp/balena"
});
```
SDK docs: https://github.com/balena-io/balena-sdk#documentation

**Comment by concreted** [comment]
Specifying the `dataDirectory` under `tmp` worked for me. Thanks! Closing this.

**Comment by trademark18** [comment]
This worked for me too.  Perhaps it wouldn't be too hard to query for environment variables to determine if running in Lambda, then default to `/tmp/balena` unless something is specified.  That way new users like me could run on Lambda automatically without searching GitHub Issues for this tip.

Pseudocode:
```javascript
const isLambdaEnvironment = process.env.LAMBDA_TASK_ROOT === 'true';

dataDirectory = isLambdaEnvironment ? 'whatever is default' : '/tmp/balena';
```

**Comment by thgreasi** [comment]
@trademark18 I would be more than happy to review such a PR.
I think the correct place to add that change would be here:
See: https://github.com/balena-io-modules/balena-settings-storage/blob/21b6f46df3fb7ce76489d8682751424d60f6023d/lib/local-storage.ts#L116

Probably wrapping the `new NodeStorage(dataDirectory);` call in a try catch, and try using the alternative path in case it throws and we detect that the sdk is running on LAMBDA.

On the other hand, in an effort to avoid hardcoding such case, I would be fine even with a PR that mentions this in the README.
