### ISSUE TITLE
Peer dependencies missing

### ISSUE THREAD

**Issue by vedicium** [balena-io/balena-sdk#663]
Hi,

I'm using the ```npm ls --json``` in one of my modules, but it fails to execute because the balena-sdk has some peer dependencies missing. This is the error I got:
```
npm ERR! peer dep missing: balena-auth@^2.0.0, required by balena-request@10.0.1
npm ERR! peer dep missing: resin-request@^9.0.2, required by resin-register-device@5.0.0
npm ERR! invalid: node-web-streams@0.2.2 /path/to/project/node_modules/balena-request/node_modules/node-web-streams
npm ERR! missing: web-streams-polyfill@^1.3.2, required by node-web-streams@0.2.2
```

When trying to install some of the peer dependencies, like the balena-auth@^2.0.0, the NPM installer can't find them.

I'm using Balena SDK 11.11.2.

Thanks in advance!

**Comment by thgreasi** [comment]
Thanks for reporting this.
We will be working of fixing the issue.

**Comment by thgreasi** [comment]
Opened https://github.com/balena-io-modules/resin-register-device/pull/37 and https://github.com/balena-io-modules/balena-request/pull/134 as the first steps for this.

**Comment by thgreasi** [comment]
After these https://github.com/balena-io/balena-sdk/pull/662 should fix the issue.

**Comment by thgreasi** [comment]
Hi @vedicium ,
As of v11.11.2 this shouldn't be an issue any more.
I'm closing this for now, but feel free to re-open if this is still an issue for you.
Thanks again for reporting this :+1:
