### ISSUE TITLE
Should have a method that returns the device's download progress.

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-sdk#790]

**Comment by richbayliss** [comment]
This needs more clarification around how this should be calculated, for example;

- A release with 4 services, 3 fully downloaded, 1 at 20% downloaded - shows as 80% complete
- A release with 4 services, 3 didn't change from the last release, 1 at 20% downloaded - shows as 20% and not 80%... or?

This seems to be very usage specific and not clearly defined.
