### ISSUE TITLE
Network errors hidden with catchReturn

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-sdk#805]
## Expected Behavior

* Calls like `whoami()` and `isLoggedIn()` should return a rejected promise with an error object describing the cause for the failure, for network errors such as invalid proxy configuration.
* Users (e.g. balena CLI users) and support agents are able to see the error, understand the problem and solve it (e.g. fix the proxy configuration).

## Actual Behavior

* `catchReturn(undefined)` and `catchReturn(false)` expressions returned undefined / false, hiding the underlying error:
https://github.com/balena-io/balena-sdk/blame/v12.21.0/lib/auth.coffee#L102
https://github.com/balena-io/balena-sdk/blame/v12.21.0/lib/auth.coffee#L234
* Users don't understand why it doesn't work and ask balena support to investigate. A number of engineers spend time trying to figure out what is going on, including myself.
  * _Token authentication failed_ https://forums.balena.io/t/token-authentication-failed/17948
  * _how to use balena deploy to build on device running development image_ https://forums.balena.io/t/how-to-use-balena-deploy-to-build-on-device-running-development-image/58490
  * _Proxy fails with Node.js >= 10.16.0_ https://github.com/balena-io/balena-cli/issues/1579

Note however that the commit that added the `catchReturn` lines is entitled _"Stop exposing sdk.token object",_ so it appears that "hiding" some errors was done with a purpose. The fix therefore should be more selective about what to hide, or find a different way of not exposing tokens.

**Comment by thgreasi** [comment]
Definitely makes sense.
It should probably filter the errors and only handle balena unauthorized errors.

**Comment by pdcastro** [comment]
I was playing with proxies with the CLI, and found some examples of errors that are being hidden as described:
* SELF_SIGNED_CERT_IN_CHAIN: request to https://api.balena-cloud.com/user/v1/whoami failed, reason: self signed certificate in certificate chain
* ECONNRESET: request to https://api.balena-cloud.com/user/v1/whoami failed, reason: tunneling socket could not be established, statusCode=403
* Cannot read property 'proxy' of undefined

**Comment by josecoelho** [comment]
I did some investigation based on @pdcastro findings. I hope it can be useful. I will come back to this issue soon.

I noticed that [getEmail](https://github.com/josecoelho/balena-sdk/blob/c6fb2f4a833f4fe35c56fe02e3b06cda436976b5/lib/auth.coffee#L319) does not call `catchReturn` and it was changed on f1369f0ca. Maybe it would never be able to expose `sdk.token` at this stage.

Errors are already normalized on [normalizeAuthError](https://github.com/josecoelho/balena-sdk/blob/c6fb2f4a833f4fe35c56fe02e3b06cda436976b5/lib/auth.coffee#L26), this could be used to filter `sdk.token` mentioned on f1369f0ca. But I need to go deeper to identify when `sdk.token` could be exposed in an error.

## Reproducing the issue with proxy

It's possible to reproduce a proxy error on `balena-sdk` running `balena-cli`. (Following [README#proxy-support](https://github.com/balena-io/balena-cli/blob/master/README.md#proxy-support))
```bash
export BALENARC_PROXY= # ensure proxy is disabled
balena login # you need to be logged in, otherwise, an ECONNREFUSED error happens
export BALENARC_PROXY='http://localhost:8000' # this is going to fail as I don't have a proxy running locally
balena apps # results on default login error "You have to log in to continue" without any extra information
```

## Manually testing a quick fix

- Remove line [:234`.catchReturn(false)`](https://github.com/josecoelho/balena-sdk/blob/c6fb2f4a833f4fe35c56fe02e3b06cda436976b5/lib/auth.coffee#L234) from `isLoggedIn`
- rebuild `balena-sdk`
- run `balena-cli` from source (linked to `balena-sdk` using `npm link`)
```bash
export BALENARC_PROXY= # ensure proxy is disabled
bin/balena-dev login # you need to be logged in, otherwise an ECONNREFUSED error happens
export BALENARC_PROXY='http://localhost:8000' # this is going to fail as I don't have a proxy running locally
bin/balena-dev apps # expected error about proxy failure (no token exposed to command line result)
DEBUG=1 bin/balena-dev apps # expected error about proxy failure (no token exposed as well)
```
Error: `ECONNRESET: request to https://api.balena-cloud.com/user/v1/whoami failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8000`

I still need to inspect the promise error object to ensure there is no extra data that might have `sdk.token`.

## Next step

- [ ] Identify what is `sdk.token` in the current codebase and which errors could expose it

That's what I have for now.

**Comment by pdcastro** [comment]
> linked to `balena-sdk` using `npm link`

@josecoelho, if `npm link` is working for you then it's all good, but in my past experience it was a bit of hit-and-miss... What I and others ended up doing is copying (I personally like [rsync](https://linux.die.net/man/1/rsync)) the relevant folders (build) from the dependency module (balena-sdk) to the `node_modules` folder of balena-cli.

**Comment by thgreasi** [comment]
@josecoelho @pdcastro thanks for this detailed issue report :+1: 
I've just opened https://github.com/balena-io/balena-sdk/pull/823 to fix this issue and I'm going through again a few cli commands that the issue was manifesting to make sure it's indeed fixed.

**Comment by pdcastro** [comment]
Thank you @thgreasi 👍  Of course you didn't know it, but @josecoelho had written to me via LinkedIn that he was hoping to work on this issue as something to add to a job application to balena, and your PR may have spoiled that plan a little bit - lol. :-)
