### ISSUE TITLE
ShortUUIDs don't work with `models.device.get` if they have no alpha characters.

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-sdk#826]
`models.device.get` accepts Device ID, UUID, or ShortUUID.  However, if the ShortUUID only contains numerical values (e.g. `8051271` as in [this example](https://github.com/balena-io/balena-cli/issues/1456)), then device will not be found.

This appears to be caused by [this line](https://github.com/balena-io/balena-sdk/blob/85e4c8842e7ad44dcf6c66584a1fa79919b1b482/lib/models/device.coffee#L328).  The utility function `isId()` is mapped to `lodash/isNumber`, so `isId()` will incorrectly return true for ShoortUUIDs with no alpha characters.

**Comment by thgreasi** [comment]
@srlowe is using `_.isNumber` which returns `false` for strings.
This is probably a bug on the CLI side, where capitano is inferring & parsing numeric-only short uuids as numbers.
That's already handled in other actions using either the `normalizeUuidProp` util function, or by directly using the `propname_raw` variant (I did fix a few of them back then :smile:) 
See: https://github.com/balena-io/balena-cli/search?q=normalizeUuidProp&unscoped_q=normalizeUuidProp
